SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT INFO.USER_ID) AS USERS
FROM USER_INFO INFO JOIN ONLINE_SALE SALE ON INFO.USER_ID = SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
