SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_INS AS INS JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.DATETIME IS NOT NULL
ORDER BY (OUTS.DATETIME - INS.DATETIME) + 1 DESC
LIMIT 2;