# SELECT YEAR(JOINED) AS YEAR, MONTH(JOINED) AS MONTH, COUNT(DISTINCT SALE.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT SALE.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) AS PUCHASED_RATIO
# FROM USER_INFO INFO JOIN ONLINE_SALE SALE ON INFO.USER_ID = SALE.USER_ID
# WHERE YEAR(JOINED) = '2021'
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH;
SELECT DATE_FORMAT(ONLINE.sales_date, '%Y') YEAR,
       DATE_FORMAT(ONLINE.sales_date, '%m') MONTH,
       COUNT(DISTINCT ONLINE.user_id) PUCHASED_USERS,
       round(COUNT(DISTINCT ONLINE.user_id) 
             / (SELECT COUNT(user_id)
                FROM user_info
                WHERE DATE_FORMAT(joined, '%Y') = '2021'), 1) PUCHASED_RATIO
FROM user_info USERINFO JOIN online_sale ONLINE
     on (USERINFO.user_id = ONLINE.user_id) 
WHERE DATE_FORMAT(USERINFO.joined, '%Y') = '2021'
GROUP BY YEAR, MONTH