SELECT ECOLI_DATA.ID ID, IFNULL(WIN.CNT, 0) CHILD_COUNT
FROM ECOLI_DATA LEFT JOIN (SELECT PARENT_ID, COUNT(*) CNT
                                FROM ECOLI_DATA
                                GROUP BY PARENT_ID) AS WIN ON ECOLI_DATA.ID = WIN.PARENT_ID

