SELECT DISTINCT F.USER_ID, F.PRODUCT_ID
FROM ONLINE_SALE F LEFT JOIN ONLINE_SALE S ON F.USER_ID = S.USER_ID
WHERE F.SALES_DATE != S.SALES_DATE AND F.PRODUCT_ID = S.PRODUCT_ID
ORDER BY F.USER_ID ASC, PRODUCT_ID DESC;