# SELECT DISTINCT NOW.USER_ID USER_ID, NOW.PRODUCT_ID PRODUCT_ID
# FROM ONLINE_SALE NOW LEFT JOIN (SELECT * FROM ONLINE_SALE) RE ON NOW.USER_ID = RE.USER_ID
# WHERE NOW.PRODUCT_ID = RE.PRODUCT_ID AND NOW.SALES_DATE != RE.SALES_DATE
# ORDER BY NOW.USER_ID ASC, PRODUCT_ID DESC;

SELECT DISTINCT OWN.USER_ID, OWN.PRODUCT_ID
FROM ONLINE_SALE OWN LEFT JOIN ONLINE_SALE COPY ON OWN.USER_ID = COPY.USER_ID
WHERE OWN.PRODUCT_ID = COPY.PRODUCT_ID AND OWN.SALES_DATE != COPY.SALES_DATE
ORDER BY OWN.USER_ID ASC, OWN.PRODUCT_ID DESC;

