# SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT IF(SALES_DATE IS NULL, 0, 1)) PURCHASED_USERS, ROUND(COUNT(DISTINCT IF(SALES_DATE IS NULL, 0, 1))/ COUNT(*), 1) PUCHASED_RATIO
# FROM (SELECT I.USER_ID, SALES_DATE, JOINED
#         FROM USER_INFO I LEFT JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
#         WHERE DATE_FORMAT(JOINED, "%Y") = "2021") AS T
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY YEAR, MONTH

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT SALE.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT SALE.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) AS PUCHASED_RATIO
FROM USER_INFO INFO JOIN ONLINE_SALE SALE ON INFO.USER_ID = SALE.USER_ID
WHERE YEAR(JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
