SELECT FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
        FROM JULY
        GROUP BY FLAVOR

        UNION ALL

        SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
        FROM FIRST_HALF
        GROUP BY FLAVOR) AS A
GROUP BY FLAVOR
ORDER BY SUM(TOTAL) DESC
LIMIT 3;