SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d")
FROM MEMBER_PROFILE P JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID IN
(SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(MEMBER_ID) = (SELECT COUNT(MEMBER_ID)
                            FROM REST_REVIEW
                            GROUP BY MEMBER_ID
                            ORDER BY COUNT(MEMBER_ID) DESC
                            LIMIT 1))
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;