SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT TREE.ITEM_ID
                  FROM ITEM_INFO AS INFO JOIN ITEM_TREE AS TREE ON INFO.ITEM_ID = TREE.PARENT_ITEM_ID
WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC;

