SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID JOIN (SELECT ITEM_ID
                            FROM ITEM_INFO
                            WHERE RARITY = 'RARE') AS WIN ON PARENT_ITEM_ID = WIN.ITEM_ID
ORDER BY I.ITEM_ID DESC;