SELECT ID, GENOTYPE, P_GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA OWN LEFT JOIN 
     (SELECT ID AS P_ID, GENOTYPE AS P_GENOTYPE FROM ECOLI_DATA) PARENT
     ON OWN.PARENT_ID = P_ID
WHERE GENOTYPE & P_GENOTYPE = P_GENOTYPE
ORDER BY ID ASC;