SELECT TITLE, B.BOARD_ID BOARD_ID, REPLY_ID, R.WRITER_ID WRITER_ID, R.CONTENTS CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") CREATED_DATE
FROM USED_GOODS_REPLY R JOIN USED_GOODS_BOARD B ON R.BOARD_ID = B.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, "%Y-%m") = "2022-10"
ORDER BY R.CREATED_DATE ASC, TITLE ASC;